// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsodwnsbnldnncyxozre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzb2R3bnNibmxkbm5jeXhvenJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2ODg4MDAsImV4cCI6MjA1MDI2NDgwMH0.iF747b-am93P08cbjLIJlTsWXRB9DS3FI_ftsY_ljk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);